
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
	<PropertyGroup>
		<AssemblyName>Stellamod</AssemblyName>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Items\Armors\Huntrian\**" />
	  <Compile Remove="Items\Armors\Huntrian\**" />
	  <EmbeddedResource Remove="Items\Armors\Huntrian\**" />
	  <None Remove="Items\Armors\Huntrian\**" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Common\WaypointSystem\UI\" />
	  <Folder Include="Items\Weapons\Melee\Knives\" />
	  <Folder Include="Items\Weapons\Ranged\Balls\" />
	  <Folder Include="Projectiles\Summons\Sentries\" />
	</ItemGroup>
</Project>