
<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.2">
  <Import Project="..\tModLoader.targets" />
	<PropertyGroup>
		<AssemblyName>Stellamod</AssemblyName>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>


	<ItemGroup>
		<Publicize Include="FNA" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
		<Publicize Include="ReLogic" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Effects\Primitives\" />
	</ItemGroup>

</Project>